<?xml version="1.0"?>
<root xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="M_SCALE" value="0.01"/>
  <xacro:property name="HOKUYO_RADIUS" value="0.02"/>
  <xacro:property name="HOKUYO_LENGTH" value="0.07"/>
  <xacro:macro name="hokuyo" params="parent name *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
		 iyy="1.0" iyz="0.0"
		 izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 -0.05" rpy="0 0 ${M_PI/2}" />
        <geometry>
          <mesh filename="package://simulator_setup/robot/rto/meshes/sensors/hokuyo.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${HOKUYO_LENGTH/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${HOKUYO_RADIUS}" length="${HOKUYO_LENGTH}" />
        </geometry>
      </collision>
    </link>
    
    <!-- gazebo extensions -->
    <xacro:hokuyo_gazebo name="${name}" ros_topic="scan" update_rate="10" min_angle="-1.570796" max_angle="1.570796"/>
    
  </xacro:macro>

  <!--GAZEBO PLUGIN-->
  <xacro:macro name="hokuyo_gazebo" params="name ros_topic update_rate min_angle max_angle">
    <gazebo reference="${name}_link">
      <sensor name="${name}" type="ray">
        <!--always_on>true</always_on-->
        <update_rate>40</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>552</samples> <!--683-->
              <resolution>1</resolution>
              <min_angle>-2.3998301029205322</min_angle> <!---2,0944-->
              <max_angle>2.3998301029205322</max_angle> <!--2,0944-->
            </horizontal>
          </scan>
          <range>
            <min>0.03</min>
            <max>5.6</max> <!--64-->
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.005</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_${name}_controller" filename="libgazebo_ros_laser.so">
          <topicName>${ros_topic}</topicName>
          <frameName>${name}_link</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  
</root>
