<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="M_SCALE" value="0.01"/>
    <xacro:property name="PLATFORM_HEIGHT" value="0.58"/>
    <xacro:property name="PLATFORM_RADIUS" value="0.22"/>
    <material name="dark_grey">
        <color rgba="${150/255} ${150/255} ${150/255} 1.0"/>
    </material>
    <!-- wheel -->
    <xacro:macro name="wheel" params="parent name *origin *axis">
        <link name="${name}_link">
            <inertial>
                <mass value="0.00001"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://simulator_setup/robot/rto/meshes/parts/rto_wheel.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
                </geometry>
            </visual>
        </link>
        <gazebo reference="${name}_link">
            <material>Gazebo/Grey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        <joint name="${name}_joint" type="fixed">
            <xacro:insert_block name="origin" />
            <xacro:insert_block name="axis"/>
            <parent link="${parent}"/>
            <child link="${name}_link"/>
        </joint>
        <!-- ToDo: Comment out and use to turn the mecanum -->
        <!-- <transmission name="${name}_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReducation>1</mechanicalReducation>
            </actuator>
        </transmission> -->
    </xacro:macro>
    <!-- command bridge -->
    <xacro:macro name="command_bridge" params="parent name *origin">
        <link name="${name}_link">
            <inertial>
                <mass value="0.00001"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
            <!-- <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.25 0.11 0.16"/>
                </geometry>
            </collision> -->
        </link>
        <joint name="${name}_joint" type="fixed">
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="${name}_link"/>
        </joint>
    </xacro:macro>
    <!-- angle bracket with USB hub -->
    <xacro:macro name="anglebracketusb" params="parent name *origin">
        <link name="${name}_link">
            <inertial>
                <mass value="0.00001"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://simulator_setup/robot/rto/meshes/parts/angle_bracket_usb_hub.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
                </geometry>
            </visual>
        </link>
        <joint name="${name}_joint" type="fixed">
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="${name}_link"/>
        </joint>
    </xacro:macro>
    <!-- platform -->
    <xacro:macro name="platform" params="parent name *origin">
        <link name="${name}_link">
            <inertial>
                <mass value="0.00001"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
            <visual>
                <origin xyz="0 0 ${PLATFORM_HEIGHT/2}"/>
                <geometry>
                    <cylinder radius="0.04" length="${PLATFORM_HEIGHT}"/>
                </geometry>
            </visual>
            <visual>
                <origin xyz="0 0 ${PLATFORM_HEIGHT}"/>
                <geometry>
                    <!-- actual length = 0.015 -->
                    <cylinder radius="${PLATFORM_RADIUS}" length="0.02"/>
                </geometry>
            </visual>
        </link>
        <joint name="${name}_joint" type="fixed">
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="${name}_link"/>
        </joint>
    </xacro:macro>
    <!-- Lochplatte -->
    <xacro:macro name="plate" params="parent name">
        <link name="${name}_link">
            <inertial>
                <mass value="0.00001"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0.12"/>
                <geometry>
                    <box size="0.002 0.06 0.24"/>
                </geometry>
                <material name="dark_grey"/>
            </visual>
        </link>
        <gazebo reference="${name}_link">
            <material>Gazebo/Grey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        <joint name="${name}_joint" type="fixed">
            <!-- <xacro:insert_block name="origin"/> -->
            <origin xyz="0.05 0 0.07"/>
            <parent link="${parent}"/>
            <child link="${name}_link"/>
        </joint>
    </xacro:macro>
    <!-- Bracket -->
    <xacro:macro name="bracket" params="parent name scale *origin">
        <link name="${name}_link">
            <inertial>
                <mass value="0.00001"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://simulator_setup/robot/rto/meshes/parts/bracket.dae" scale="0.001 ${scale} ${scale}"/>
                </geometry>
                <material name="dark_grey"/>
            </visual>
        </link>
        <gazebo reference="${name}_link">
            <material>Gazebo/DarkGrey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        <joint name="${name}_joint" type="fixed">
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="${name}_link"/>
        </joint>
    </xacro:macro>
</robot>
