<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="M_SCALE" value="0.01"/>
    <xacro:property name="BASE_RADIUS" value="0.18"/>
    <xacro:property name="BASE_HEIGHT" value="0.05"/>
    <xacro:property name="BASE_MASS" value="20"/>
    <!-- rto_body -->
    <xacro:macro name="rto_body">
        <!-- base_link -->
        <link name="base_link">
            <inertial>
                <mass value="${BASE_MASS}" />
                <origin xyz="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
            <visual>
                <origin xyz="0.01 0 0" rpy="0 0 ${M_PI/2}"/>
                <geometry>
                    <mesh filename="package://simulator_setup/robot/rto/meshes/parts/rto_base.dae"
                        scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${BASE_RADIUS}" length="${BASE_HEIGHT}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="base_link">
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
        <!-- wheels -->
        <xacro:wheel name="wheel0" parent="base_link">
            <origin xyz="0.065 0.11 0.04" rpy="0 0 ${M_PI/3}"/>
            <axis xyz="-1 0 0"/>
        </xacro:wheel >
        <xacro:wheel  name="wheel1" parent="base_link">
            <origin xyz="-0.13 0 0.04" rpy="0 0 0"/>
            <axis xyz="1 0 0"/>
        </xacro:wheel >
        <xacro:wheel  name="wheel2" parent="base_link">
            <origin xyz="0.065 -0.11 0.04" rpy="0 0 -${M_PI/3}"/>
            <axis xyz="-1 0 0"/>
        </xacro:wheel >
        <!-- others -->
        <xacro:command_bridge name="command_bridge" parent="base_link">
            <origin xyz="-0.05 0 0.13" rpy="0 0 ${M_PI/2}"/>
        </xacro:command_bridge>
        <!-- <xacro:anglebracketusb name="anglebracketusb" parent="base_link">
            <origin xyz="0.008 0 0.137" rpy="0 0 ${M_PI/2}"/>
        </xacro:anglebracketusb> -->
        <!-- gazebo control -->
        <gazebo>
            <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
                <commandTopic>cmd_vel</commandTopic>
                <odometryTopic>odom</odometryTopic>
                <odometryFrame>odom</odometryFrame>
                <odometryRate>20</odometryRate>
                <robotBaseFrame>base_link</robotBaseFrame>
                <publishTF>true</publishTF>
            </plugin>
            <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
        </gazebo>
    </xacro:macro>
</robot>
